name: CI for Hello World

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7.6
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with:
        repository: lowkh/DevOps2022Demo
    - name: list our contents
      run: |
        ls
    - name: test with pytest
      run: |
        pytest test.py -v -cov

    - if: ${{ failure() }}
      uses: mrdoodles/issue-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Some Issue Title
        body: Some Issue Body
        assignees: ${{github.actor}}
